enum user_input_name{ACCEL, BRAKE, STEER, NUM_DUMMY};
enum torcs_output_name{CC_TRIGGER, LKAS_TRIGGER, SPEED, RPM, TRACK_ANGLE, TRACK_WIDTH, YAW, DISTANCE, PASSED_TIME, IS_RUNNING, TRACK_NUM,
TRACK_TYPE, TRACK_TYPE1, TRACK_TYPE2, TRACK_TYPE3, TRACK_TYPE4, TRACK_TYPE5, TRACK_TYPE6, TRACK_TYPE7, TRACK_TYPE8, TRACK_TYPE9,
TRACK_TYPE10, TRACK_TYPE11, TRACK_TYPE12, TRACK_TYPE13, TRACK_TYPE14, TRACK_TYPE15, TRACK_TYPE16, TRACK_TYPE17, TRACK_TYPE18, TRACK_TYPE19,
TRACK_RADIUS, TRACK_RADIUS1, TRACK_RADIUS2, TRACK_RADIUS3, TRACK_RADIUS4, TRACK_RADIUS5, TRACK_RADIUS6, TRACK_RADIUS7, TRACK_RADIUS8, TRACK_RADIUS9,
TRACK_RADIUS10, TRACK_RADIUS11, TRACK_RADIUS12, TRACK_RADIUS13, TRACK_RADIUS14, TRACK_RADIUS15, TRACK_RADIUS16, TRACK_RADIUS17, TRACK_RADIUS18, TRACK_RADIUS19,
TRACK_FRICTION, TRACK_FRICTION1, TRACK_FRICTION2, TRACK_FRICTION3, TRACK_FRICTION4, TRACK_FRICTION5, TRACK_FRICTION6, TRACK_FRICTION7, TRACK_FRICTION8, TRACK_FRICTION9,
TRACK_FRICTION10, TRACK_FRICTION11, TRACK_FRICTION12, TRACK_FRICTION13, TRACK_FRICTION14, TRACK_FRICTION15, TRACK_FRICTION16, TRACK_FRICTION17, TRACK_FRICTION18, TRACK_FRICTION19};
